//! **Problem 2**: Even Fibonacci numbers
//!
//! Each new term in the Fibonacci sequence is generated by adding the previous
//! two terms. By starting with 1 and 2, the first 10 terms will be:
//!
//! `1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...`
//!
//! By considering the terms in the Fibonacci sequence whose values do not
//! exceed four million, find the sum of the even-valued terms.
//!
//! [Problem 2 on projecteuler.net](https://projecteuler.net/problem=2)
//!

use crate::util::Fibonacci;

/// Calculate solution to Problem 2
pub fn solution() -> String {
    Fibonacci::<usize>::one()
        .filter(|i| i % 2 == 0)
        .take_while(|i| *i < 4_000_000)
        .sum::<usize>()
        .to_string()
}

#[test]
fn test_solution() {
    assert_eq!("4613732", solution());
}
